dist: bionic
language: c
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
env:
  global:
    - PINS="dtc-pb:."
  jobs:
    - OCAML_VERSION="4.09" PACKAGE="dtc-pb"
os:
- linux
